---
# Readiness failure application - never becomes ready
apiVersion: apps/v1  
kind: Deployment
metadata:
  name: readiness-failure
  namespace: k8sgpt-demo
  labels:
    app: readiness-failure
    demo-scenario: readiness-failure
spec:
  replicas: 2
  selector:
    matchLabels:
      app: readiness-failure
  template:
    metadata:
      labels:
        app: readiness-failure
        demo-scenario: readiness-failure
    spec:
      containers:
      - name: failing-readiness
        image: nginx:1.21-alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "64Mi"
            cpu: "50m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /nonexistent  # This endpoint doesn't exist, causing readiness failure
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
      restartPolicy: Always

---
# Service for readiness failure application
apiVersion: v1
kind: Service
metadata:
  name: readiness-failure-svc
  namespace: k8sgpt-demo
  labels:
    app: readiness-failure
spec:
  selector:
    app: readiness-failure
  ports:
  - port: 80
    targetPort: 80
    name: http
  type: ClusterIP