# K8sGPT Operator Helm values for comprehensive demo
# Configured for integration with Prometheus/Alertmanager

# Global settings
nameOverride: "k8sgpt-operator"
fullnameOverride: "k8sgpt-operator"

# Operator configuration
operator:
  # Resource limits for Kind cluster
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "200m"
  
  # Enable metrics for Prometheus scraping
  metrics:
    enabled: true
    port: 8080
    service:
      type: ClusterIP
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"

# Enable interplex for remote caching (optional)
interplex:
  enabled: true
  resources:
    requests:
      memory: "64Mi"
      cpu: "25m"  
    limits:
      memory: "128Mi"
      cpu: "100m"

# ServiceMonitor for Prometheus integration  
serviceMonitor:
  enabled: true
  namespace: "monitoring"
  labels:
    app.kubernetes.io/name: k8sgpt-operator
  interval: 30s
  path: /metrics

# Additional configuration for demo
config:
  # Enable additional analyzers
  analyzers:
    - Pod
    - Service  
    - Deployment
    - ReplicaSet
    - PersistentVolumeClaim
    - Ingress
    - Node
  
  # Analysis configuration
  analysis:
    # Run analysis every 2 minutes for demo responsiveness
    interval: "2m"
    # Enable analysis of all namespaces
    allNamespaces: true