kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: k8sgpt-demo
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  # Prometheus
  - containerPort: 30090
    hostPort: 9090
    protocol: TCP
  # Alertmanager  
  - containerPort: 30093
    hostPort: 9093
    protocol: TCP
  # Grafana (optional)
  - containerPort: 30080
    hostPort: 3000
    protocol: TCP
- role: worker
- role: worker
# Increase resource limits for demo workloads
networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6443