# Prometheus-stack Helm values for k8sgpt-operator demo
# Optimized for Kind cluster with monitoring and alerting

# Global settings
fullnameOverride: "kube-prometheus-stack"

# Prometheus configuration
prometheus:
  enabled: true
  prometheusSpec:
    # Resource limits for Kind cluster
    resources:
      requests:
        memory: "400Mi"
        cpu: "100m"
      limits:
        memory: "800Mi" 
        cpu: "500m"
    
    # Storage configuration
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: standard
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi
    
    # Enable service monitor for k8sgpt metrics
    serviceMonitorSelectorNilUsesHelmValues: false
    
    # Retention settings
    retention: "7d"
    retentionSize: "4GB"
    
    # Additional scrape configs for k8sgpt
    additionalScrapeConfigs:
    - job_name: 'k8sgpt-operator'
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
          - k8sgpt-operator-system
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        action: keep
        regex: k8sgpt-operator-metrics

  # Service configuration for external access
  service:
    type: NodePort
    nodePort: 30090

# Alertmanager configuration  
alertmanager:
  enabled: true
  alertmanagerSpec:
    # Resource limits for Kind cluster
    resources:
      requests:
        memory: "200Mi"
        cpu: "50m"
      limits:
        memory: "400Mi"
        cpu: "200m"
    
    # Storage configuration  
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: standard
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi
    
    # Custom configuration
    configSecret: alertmanager-config
  
  # Service configuration for external access
  service:
    type: NodePort
    nodePort: 30093

# Grafana configuration (optional but useful)
grafana:
  enabled: true
  adminPassword: "admin123"
  service:
    type: NodePort
    nodePort: 30080
  
  # Resource limits for Kind cluster
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "200m"

# Node Exporter
nodeExporter:
  enabled: true

# kube-state-metrics
kube-state-metrics:
  enabled: true
  
# Default rules and alerts
defaultRules:
  create: true
  rules:
    # Enable specific rule groups for k8sgpt integration
    alertmanager: true
    etcd: false  # Disable for Kind
    configReloaders: true
    general: true
    k8s: true
    kubeApiserver: false  # Can be noisy in Kind
    kubeApiserverAvailability: true
    kubeApiserverSlos: false
    kubeApiserverHistogram: false
    kubePrometheusGeneral: true
    kubePrometheusNodeRecording: true
    kubernetesApps: true
    kubernetesResources: true
    kubernetesStorage: true
    kubernetesSystem: true
    kubeSchedulerAlerting: false  # Disable for Kind
    kubeSchedulerRecording: false
    kubeStateMetrics: true
    network: true
    node: true
    nodeExporter: true
    prometheus: true
    prometheusOperator: true

# Disable components not needed for demo
kubeApiServer:
  enabled: false
kubeControllerManager:
  enabled: false  
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false
kubelet:
  enabled: true
kubeEtcd:
  enabled: false